services:
  db:
    image: postgres:15-alpine
    container_name: postgres_t2
    restart: always
    environment:
      - POSTGRES_DB=t2_seguranca
      - POSTGRES_USER=sandro
      - POSTGRES_PASSWORD=minhasenha
    ports:
      - "5432:5432"  # Mapeia a porta do container para o seu PC